Shedule.Web/ViewModels/TeachingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shedule.Web.ViewModels
{
    public class TeachingViewModel
    {
        public TeachingViewModel()
        {
            this.Lessons = new List<LessonViewModel>();
            this.Tariffs = new List<TariffItemViewModel>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public float Price { get; set; }

        public List<LessonViewModel> Lessons { get; set; }

        public List<TariffItemViewModel> Tariffs { get; set; }

        public class TariffItemViewModel 
        {
            public int Id { get; set; }

            public string Title { get; set; }

            public int CountOfPairs { get; set; }

            public int Price { get; set; }
        }
    }
}

Shedule.Web/Controllers/SheduleController.cs
using AutoMapper;
using Newtonsoft.Json;
using Shedule.Business;
using Shedule.Data.Model;
using Shedule.Web.Helpers;
using Shedule.Web.Models;
using Shedule.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shedule.Web.Controllers
{
    [Authorize]
    public class SheduleController : Controller
    {
        public SheduleController()
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SheduleForTeaching(int teachingId)
        {
            SheduleForTeachingViewModel model = new SheduleForTeachingViewModel();
            
            using (BusinessContext businessContext = new BusinessContext())
            {
                var teaching = businessContext.TeachingManager.Get(teachingId);
                model.TeachingName = teaching.Name;
                model.TeachingId = teaching.Id;
                
                foreach (var lesson in teaching.Lessons)
                {
                    model.Days[lesson.DayNumber].Lessons.Add(new SheduleDayViewModel.LessonViewModel()
                    {
                        Id = lesson.Id,
                        Name = lesson.Teaching.Name,
                        PeriodNumber = lesson.PeriodNumber,
                        ClassroomName = lesson.Classroom.Name,
                        TeacherName = string.Format("{0} {1}", lesson.Teacher.FirstName, lesson.Teacher.LasName)
                    });
                }
            }

            return View(model);
        }

        public ActionResult SheduleForDay(int dayNumber)
        {
            SheduleForDayViewModel model = new SheduleForDayViewModel();

            using (BusinessContext businessContext = new BusinessContext())
            {
                var lessons = businessContext.LessonManager.AllForDay(dayNumber);
                var groupedLessons = lessons.GroupBy(l => l.Classroom.Name).ToList();
                model.DayOfWeek = dayNumber;
                foreach(var group in groupedLessons)
                {
                    List<LessonItemViewModel> list = new List<LessonItemViewModel>();
                    
                    foreach (var lesson in group)
                    {
                        LessonItemViewModel lessonViewModel = new LessonItemViewModel()
                        {
                            Name = lesson.Teaching.Name,
                            Id = lesson.Id,
                        };
                        list.Add(lessonViewModel);
                    }

                    model.Lessons.Add(group.Key, list);
                }
            }

            return View(model);
        }

        public ActionResult SheduleForSchoolboy(int schoolboyId)
        {
            var model = new SheduleForSchoolboy();
            using (BusinessContext businessContext = new BusinessContext())
            {
                var schoolboy = businessContext.LessonManager.SchoolboyWithLessons(schoolboyId);
                var lessons = schoolboy.SchoolboyToTariffs.Select(st => st.Lesson).ToList();
                model.FirstName = schoolboy.FirstName;
                model.LastName = schoolboy.LastName;
                model.SchoolboyId = schoolboy.Id;
                foreach (var lesson in lessons)
                {
                    model.Days[lesson.DayNumber].Lessons.Add(new SheduleDayViewModel.LessonViewModel()
                    {
                        Id = lesson.Id,
                        Name = lesson.Teaching.Name,
                        PeriodNumber = lesson.PeriodNumber,
                        ClassroomName = lesson.Classroom.Name,
                        TeacherName = string.Format("{0} {1}", lesson.Teacher.FirstName, lesson.Teacher.LasName),
                        TeachingId = lesson.Teacher.Id,
                    });
                }

                var teachings = businessContext.TeachingManager.All();
                foreach (var teaching in teachings)
                {
                    var modelForTeaching = new LessonsAndTarifsForTeachingViewModel();
                    foreach (var lesson in teaching.Lessons)
                    {
                        modelForTeaching.Lessons.Add(new LessonsAndTarifsForTeachingViewModel.LessonItemViewModel()
                        {
                            FormattedTimeAndDay = string.Format("{0}, {1} ({2})", 
                                DateHelper.GetDayNameByNumber(lesson.DayNumber),
                                DateHelper.GetFormattedTimeByPeriodNumber(lesson.PeriodNumber),
                                lesson.Classroom.Name),
                            LessonId = lesson.Id,
                        });
                    }

                    foreach (var tariff in teaching.Tariffs)
                    {
                        modelForTeaching.Tariffs.Add(new LessonsAndTarifsForTeachingViewModel.TariffItemViewModel()
                        {
                            TariffId = tariff.Id,
                            FormattedInfo = string.Format("{0}, {1} занятий/{2} грн", tariff.Title, tariff.CountOfPairs, tariff.Price),
                        });
                    }

                    model.Teachings.Add(new SelectListItem()
                    {
                        Text = teaching.Name,
                        Value = JsonConvert.SerializeObject(modelForTeaching),
                    });
                }
                
            }

            return View(model);
        }

        public ActionResult SheduleForTeacher(int teacherId)
        {
            var model = new SheduleForTeacher();
            using (BusinessContext businessContext = new BusinessContext())
            {
                var teacher = businessContext.TeacherManager.Get(teacherId);
                
                model.FirstName = teacher.FirstName;
                model.LastName = teacher.LasName;
                model.TeacherId = teacher.Id;
                foreach (var lesson in teacher.Lessons)
                {
                    model.Days[lesson.DayNumber].Lessons.Add(new SheduleDayViewModel.LessonViewModel()
                    {
                        Id = lesson.Id,
                        Name = lesson.Teaching.Name,
                        PeriodNumber = lesson.PeriodNumber,
                        ClassroomName = lesson.Classroom.Name,
                        TeacherName = string.Format("{0} {1}", lesson.Teacher.FirstName, lesson.Teacher.LasName),
                        TeachingId = lesson.Teacher.Id,
                    });
                }

                var teachings = businessContext.TeachingManager.All();
                foreach (var teaching in teachings)
                {
                    var modelForTeaching = new LessonsAndTarifsForTeachingViewModel();
                    foreach (var lesson in teaching.Lessons)
                    {
                        modelForTeaching.Lessons.Add(new LessonsAndTarifsForTeachingViewModel.LessonItemViewModel()
                        {
                            FormattedTimeAndDay = string.Format("{0}, {1} ({2})",
                                DateHelper.GetDayNameByNumber(lesson.DayNumber),
                                DateHelper.GetFormattedTimeByPeriodNumber(lesson.PeriodNumber),
                                lesson.Classroom.Name),
                            LessonId = lesson.Id,
                        });
                    }

                    model.Teachings.Add(new SelectListItem()
                    {
                        Text = teaching.Name,
                        Value = JsonConvert.SerializeObject(modelForTeaching),
                    });
                }

            }

            return View(model);
        }
    }
}

Shedule.Web/Controllers/TeachingController.cs
using AutoMapper;
using Shedule.Business;
using Shedule.Data.Model;
using Shedule.Web.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Shedule.Web.Controllers
{
    [Authorize]
    public class TeachingController : Controller
    {
        public TeachingController()
        {
            Mapper.CreateMap<Lesson, LessonViewModel>();
            Mapper.CreateMap<Tariff, TeachingViewModel.TariffItemViewModel>();
            Mapper.CreateMap<Teaching, TeachingViewModel>();
        }

        // GET: Teaching
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            List<Teaching> list = new List<Teaching>();
            using (BusinessContext businessContext = new BusinessContext())
            {
                list = businessContext.TeachingManager.All();
            }

            List<TeachingViewModel> teachings = new List<TeachingViewModel>();
            foreach (var teaching in list)
            {
                TeachingViewModel model = new TeachingViewModel();
                model.Id = teaching.Id;
                model.Name = teaching.Name;
                model.Price = teaching.Price;

                foreach (var lesson in teaching.Lessons)
                {

                }

                teachings.Add(model);
            }
            return View(teachings);
        }

        /// <summary>
        /// Gets the specified teaching identifier.
        /// </summary>
        /// <param name="teachingId">The teaching identifier.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Get(int teachingId)
        {

            using (BusinessContext businessContext = new BusinessContext())
            {
                var teaching = businessContext.TeachingManager.Get(teachingId);
                TeachingViewModel model = Mapper.Map<Teaching, TeachingViewModel>(teaching);
                model.Tariffs = Mapper.Map<List<Tariff>, List<TeachingViewModel.TariffItemViewModel>>(teaching.Tariffs);
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TeachingViewModel model)
        {
            using (BusinessContext businessContext = new BusinessContext())
            {
                Teaching teaching = Mapper.Map<TeachingViewModel, Teaching>(model);
                businessContext.TeachingManager.Create(teaching);
            }

            return RedirectToAction("Index", "Teaching");
        }

        public ActionResult Delete(int teachingId)
        {
            using (BusinessContext businessContext = new BusinessContext())
            {
                businessContext.TeachingManager.Delete(teachingId);
            }

            return RedirectToAction("Index", "Teaching");
        }

        [HttpPost]
        [Authorize(Roles="admin")]
        public ActionResult AddTariff(AddTariffViewModel model)
        {
            using (BusinessContext businessContext = new BusinessContext())
            {
                businessContext.TeachingManager.AddTariff(
                    model.TeachingId,
                    model.Title,
                    model.CountOfPairs,
                    model.Price);
            }

            return RedirectToAction("Get", new { teachingId = model.TeachingId});
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteTariff(int tariffId, int teachingId)
        {
            using (BusinessContext businessContext = new BusinessContext())
            {
                businessContext.TeachingManager.DeleteTariff(tariffId);
            }

            return RedirectToAction("Get", new { teachingId = teachingId});
        }
    }
}

Shedule.Web/Views/Teaching/Create.cshtml
@model Shedule.Web.ViewModels.TeachingViewModel

@{
    ViewBag.Title = "Добавить предмет";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Название предмета</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                <span class="field-validation-valid text-danger" data-valmsg-for="Введите название предмета" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Цена за обучение, грн/занятие</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                <span class="field-validation-valid text-danger" data-valmsg-for="Введите цену за обучение" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать предмет" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку предметов", "Index")
</div>

Shedule.Web/Views/Teaching/Get.cshtml
@model Shedule.Web.ViewModels.TeachingViewModel

@{
    ViewBag.Title = "О предмете";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <br />
    <h4>Информация о предмете</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Название: </label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            <label>Цена, грн/урок</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    <hr />
    <br />
    <h4>Тарифы для предмета</h4>
    <table class="table">
        <tr>
            <th>
                Название тарифа
            </th>
            <th>
                Количество занятий
            </th>
            <th>
                Стоимость, грн
            </th>
            @if (this.Context.User.IsInRole("admin"))
            {

                <th></th>
            }
        </tr>
        @foreach (var tariff in Model.Tariffs)
        {
            <tr>
                <th>
                    @tariff.Title
                </th>
                <th>
                    @tariff.CountOfPairs
                </th>
                <th>
                    @tariff.Price
                </th>
                @if (this.Context.User.IsInRole("admin"))
                {
                    <th>
                        @using (Html.BeginForm("DeleteTariff", "Teaching", FormMethod.Post))
                        {
                            <input type="hidden" value="@Model.Id" name="teachingId" />
                            <input type="hidden" value="@tariff.Id" name="tariffId" />
                            <input type="submit" value="Удалить" />
                        }
                    </th>
                }
            </tr>
        }
    </table>
    @if (this.Context.User.IsInRole("admin"))
    {
        <hr />
        <br />
        <h4>Добавить тариф</h4>
        using (Html.BeginForm("AddTariff", "Teaching", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <input type="hidden" value="@Model.Id" name="teachingId" />
                <div class="form-group">
                    <label class="control-label col-md-2">Название тарифа</label>
                    <div class="col-md-10">
                        <input type="text" required name="title" class="form-control" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="Введите название тарифа" data-valmsg-replace="true"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Количество занятий</label>
                    <div class="col-md-10">
                        <input type="number" required name="countOfPairs" class="form-control" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="Введите количество занятий" data-valmsg-replace="true"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Цена за тариф</label>
                    <div class="col-md-10">
                        <input type="number" required name="price" class="form-control" />
                        <span class="field-validation-valid text-danger" data-valmsg-for="Введите цену за обучение" data-valmsg-replace="true"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Добавить" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    }
    

</div>
<p>
    @Html.ActionLink("Вернуться к списку предметов", "Index")
</p>

Shedule.Web/Views/Teaching/Index.cshtml
@model List<Shedule.Web.ViewModels.TeachingViewModel>

@{
    ViewBag.Title = "Предметы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<p>
    @Html.ActionLink("Добавить новый предмет", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Название предмета
        </th>
        <th>
            Цена грн/час
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Расписание", "SheduleForTeaching", "Shedule", new { teachingId = item.Id }, new object { })
        </td>
        <td>
            @Html.ActionLink("Добавить урок", "Add", "Lesson", new { }, new object { })
        </td>
        <td>
            @*@Html.ActionLink("Редактировать", "Edit", new { /* id=item.PrimaryKey */ }) |*@
            @Html.ActionLink("Детали", "Get", new { teachingId = item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { teachingId = item.Id })
        </td>
    </tr>
}

</table>